site_name: Indy Center Tech Docs
site_url: https://docs.zid-internal.com
repo_url: https://github.com/Indy-Center/docs
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
    - scheme: default
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: deep-orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - navigation.indexes
    - content.action.edit
    - content.action.view

plugins: 
  - search
  - macros:
      include_dir: partials


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: Copyright &copy; 2025 Indy Center. <br />This site is not affiliated with the Federal Aviation Administration or any governing aviation body. All content contained herein is approved only for use on the VATSIM network.

extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/quYNCbnDfw